source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'rspec'
gem 'pry'
gem 'activesupport', require: 'active_support/all'
gem 'rake'
gem 'thin'
gem 'rdiscount'
gem 'sinatra-partial'
gem 'dotenv'
gem 'omniauth-github'
gem 'json'
gem 'sinatra-formhelpers'
gem 'stamp'