source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem "therubyracer"
gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem "twitter-bootstrap-rails"
gem 'bootswatch-rails'
gem 'chosen-rails'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'xpath'
gem 'nested_form'
gem 'nokogiri'
# Gems used only for assets and not required
# in production environments by default.
gem 'postmark-rails', '0.4.1'
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-ui-rails'
end

gem 'carrierwave'
gem 'rubyzip'
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

gem 'uglifier', '>= 1.0.3'
gem 'jquery-rails'
# To use ActiveModel has_secure_password
gem 'bcrypt-ruby', '~> 3.0.0'
gem "declarative_authorization", "~> 0.5.6"
# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
group :development, :test do
  gem 'debugger'
  gem 'pry'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'rb-fsevent', '~> 0.9.1'
  gem 'terminal-notifier-guard'
  gem 'capybara'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'sqlite3'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
end

group :production do
  gem "whenever", "~> 0.8.0"

  gem 'pg'
  gem 'exception_notification'
end

gem 'simplecov', :require => false, :group => :test
