source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
 
group :development do
  gem 'sqlite3'
  gem 'sinatra-reloader'
  gem "tux" # run tux in terminal as console.
end