secret_token: "YOUR SECRET TOKEN"

development:
  github_client_id: "YOUR APP CLIENT ID"
  github_client_secret: "YOUR APP CLIENT SECRET"

test:
  github_client_id: "YOUR APP CLIENT ID"
  github_client_secret: "YOUR APP CLIENT SECRET"

production:
  github_client_id: "YOUR APP CLIENT ID"
  github_client_secret: "YOUR APP CLIENT SECRET"
  notifier_sender_address: "your exception notifier sender address"
  notifier_recipients: "comma separated list of exception recipients"
  postmark_api_key: "Your Postmark API Key if you're using Postmark, else configure your own Actionmailer delivery method (see production.rb:72)"