source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


gem 'thin'
# gem 'therubyracer', :platforms => :ruby
# gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
# gem "less-rails"

gem 'whenever', :require => false

gem 'therubyracer'
gem 'less-rails' #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem 'twitter-bootstrap-rails'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-github'
gem 'chronic'
gem 'aasm'
gem 'jquery-tablesorter'
gem 'redcarpet'
gem 'pygments.rb'
gem 'postmark-rails'
gem 'rake', '10.0.2'
gem 'pg'
gem 'jquery-hotkeys-rails'
gem 'bcrypt-ruby', :require => 'bcrypt'
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'jquery-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes

  gem 'uglifier', '>= 1.0.3'
end
group :production do

end

group :development, :test do
  gem 'powder'
  gem 'sextant'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'rb-fsevent'
  gem 'timecop'
  gem 'guard-rspec'
  gem 'growl'
  gem 'launchy'
  gem 'debugger'
end

group :test do
  gem 'capybara'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'faker'
end



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
